datasource:
  driverName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/car_service_database
  login: test
  password: root
  initialSize: 10
  maxActive: 7
app:
  login: test
  token: test
  password: test