spring:
  flyway:
    ignore-missing-migrations: true
    locations: classpath:migrations
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
datasource:
  driverName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/car_service_database
  login: test
  password: root
  initialSize: 10
  maxActive: 7
app:
  login: test
  token: test
  password: test
tokenset:
  secret: secret
  expire: 1000000