package com.htp.controller;

import com.htp.controller.requests.SearchCriteria;
import com.htp.controller.requests.UserCreateRequest;
import com.htp.dao.RolesDao;
import com.htp.dao.hibernate.HibernateUser;
import com.htp.entity.Users;
import com.htp.dao.UsersDao;
import com.htp.entity.hibernate.TestUser;
import io.swagger.annotations.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;
import springfox.documentation.annotations.ApiIgnore;

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

//@Controller
@RestController
@CrossOrigin
@RequestMapping(value = "/rest/users")
public class UsersController {

    @Autowired
    @Qualifier("usersDaoImpl")
    private UsersDao userDao;

    @Autowired
    private HibernateUser hibernateUserDao;

    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<List<Users>> getUsers() {
        return new ResponseEntity<>(userDao.findAll(), HttpStatus.OK);
    }

    @GetMapping("/all")
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<List<TestUser>> getUsersHibernate() {
        return new ResponseEntity<>(hibernateUserDao.findAll(), HttpStatus.OK);
    }

    @ApiOperation(value = "Get user from server by id")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Successful getting user"),
            @ApiResponse(code = 400, message = "Invalid User ID supplied"),
            @ApiResponse(code = 401, message = "Lol kek"),
            @ApiResponse(code = 404, message = "User was not found"),
            @ApiResponse(code = 500, message = "Server error, something wrong")
    })
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public ResponseEntity<Users> getUserById(@ApiParam("User Path Id") @PathVariable Long id) {
        Users user = userDao.findById(id);
        return new ResponseEntity<>(user, HttpStatus.OK);
    }

    @Autowired
    private RolesDao roleDao;

    /**/
    /*@PostMapping
    @Transactional
    @ResponseStatus(HttpStatus.CREATED)
    public ResponseEntity<Users> createUser(@RequestBody UserCreateRequest request) {
        Users user = new Users();
        //userID is empty - will be generated by DB
        user.setUserName(request.getUserName());
        user.setUserSurname(request.getUserSurname());
        user.setBirthDate(new Timestamp(new Date().getTime()));
        user.setDepartmentId(1l); //f*cking trash

        User savedUser = userDao.save(user);
        roleDao.save(new Role(savedUser.getUserId(), "ROLE_USER"));

        return new ResponseEntity<>(savedUser, HttpStatus.OK);
    }*/

   /* @PostMapping("/test")
    @Transactional
    @ResponseStatus(HttpStatus.CREATED)
    public ResponseEntity<TestUser> createTestUser(@RequestBody UserCreateRequest request) {
        TestUser user = new TestUser();
        //userID is empty - will be generated by DB
        user.setUserName(request.getUserName());
        user.setUserSurname(request.getUserSurname());
        user.setBirthDate(new Timestamp(new Date().getTime()));

        return new ResponseEntity<>(hibernateUserDao.save(user), HttpStatus.OK);
    }*/

   /* @ApiOperation(value = "Update user by userID")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Successful user update 1111111"),
            @ApiResponse(code = 400, message = "Invalid User ID supplied 111111"),
            @ApiResponse(code = 404, message = "User was not found 111111"),
            @ApiResponse(code = 500, message = "Server error, something wrong 1111111")
    })
    @ApiImplicitParams({
            @ApiImplicitParam(name = "X-Auth-Token", value = "token", required = true, dataType = "string", paramType = "header")
    })
    @RequestMapping(value = "/{id}", method = RequestMethod.PUT)
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<User> updateUser(@PathVariable("id") Long userId,
                                           @RequestBody UserCreateRequest request) {
        User user = userDao.findById(userId);
        user.setUserName(request.getUserName());
        user.setUserSurname(request.getUserSurname());
        user.setBirthDate(new Timestamp(new Date().getTime()));
        user.setDepartmentId(1L);

        return new ResponseEntity<>(user, HttpStatus.OK);
    }*/

    /*@ApiOperation(value = "Update user by userID")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Successful user update"),
            @ApiResponse(code = 400, message = "Invalid User ID supplied"),
            @ApiResponse(code = 404, message = "User was not found"),
            @ApiResponse(code = 500, message = "Server error, something wrong")
    })
    @RequestMapping(value = "/test/{id}", method = RequestMethod.PUT)
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<TestUser> updateTestUser(@ApiParam(value = "User ID", required = false) @PathVariable("id") Long userId,
                                                   @RequestBody UserCreateRequest request) {

        hibernateUserDao.findById(userId);

        TestUser user = new TestUser();
        //userID is empty - will be generated by DB
        user.setUserId(null);
        user.setUserName(request.getUserName());
        user.setUserSurname(request.getUserSurname());
        user.setBirthDate(new Timestamp(new Date().getTime()));

        return new ResponseEntity<>(hibernateUserDao.update(user), HttpStatus.OK);
    }*/

   /* @ApiOperation(value = "Search user by query")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Successful user update"), //OK
            @ApiResponse(code = 400, message = "Invalid query supplied"), //Invalid request
            @ApiResponse(code = 404, message = "User was not found"), //Resourse not found
            @ApiResponse(code = 500, message = "Server error, something wrong")
    })
    @ApiImplicitParams({
            @ApiImplicitParam(name = "limit", value = "limit of users", required = true, dataType = "int", paramType = "query"),
            @ApiImplicitParam(name = "offset", value = "start node of users", required = true, dataType = "int", paramType = "query"),
            @ApiImplicitParam(name = "query", value = "search query", required = true, dataType = "string", paramType = "query"),
            @ApiImplicitParam(name = "X-Auth-Token", value = "token", required = true, dataType = "string", paramType = "header")
    })
    @GetMapping("/search")
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<List<User>> searchUsers(@ApiIgnore @ModelAttribute SearchCriteria search) {
        List<User> searchResult =
                userDao.search(
                        search.getQuery(),
                        search.getLimit(),
                        search.getOffset()
                );
        return new ResponseEntity<>(searchResult, HttpStatus.OK);
    }*/

    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<Long> deleteUser(@PathVariable("id") Long userId) {
        userDao.deleteById(userId);
        return new ResponseEntity<>(userId, HttpStatus.OK);
    }



/* PREVIOUS VARIANT


    private final UsersDao userDao;

    public UsersController(UsersDao userDao) {
        this.userDao = userDao;
    }

    *//*GET localhost:8080/HelloWeb/users/create*//*
    @RequestMapping(value = "/users/deleted", method = RequestMethod.GET)
    @ResponseStatus(HttpStatus.OK)
    public String printDeletedUsers(ModelMap model) {
        model.addAttribute("usersdeleted",
                userDao.findAllDeletedUsers().stream()
                        .map(Users::toString)
                        .collect(Collectors.joining("---"))
        );
        return "hello";
    }

    *//*GET localhost:8080/HelloWeb/users/all*//*
    @RequestMapping(value = "/users/all", method = RequestMethod.GET)
    @ResponseStatus(HttpStatus.OK)
    public String printAllUsers(ModelMap model) {
        model.addAttribute("usersreadall",
                userDao.findAll().stream()
                        .map(Users::toString)
                        .collect(Collectors.joining(","))
        );
        return "hello";}*/



}
